### ISSUE TITLE
Migrating one config structure to another

### ISSUE THREAD

**Issue by chris9740** [rust-cli/confy#99]
Hello! When making changes to my configuration, how can I "migrate" from one configuration structure to another?

### Current configuration:
```toml
mode = "Standard"
address = "127.0.0.1:53"
tor = true
```

### Desired configuration:
```toml
mode = "Standard"
address = "127.0.0.1:53"

[tor]
enabled = true
address = "127.0.0.1:9050"
```

Here's a repo that contains the basic code: https://github.com/chris9740/confy-migrate
